name: Build and Release Firmware

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 2. Install ESP-IDF with caching
      - name: Setup ESP-IDF and Build
        uses: rmshub/esp-idf-action@v6
        with:
          esp_idf_version: v5.4.1
          esp_idf_target: esp32
          build_command: idf.py build

      # 3. Extract firmware version and create version.txt
      - name: Create version.txt
        run: |
          VERSION=$(grep -Po '(?<=#define FIRMWARE_VERSION ")[^"]*' main/*.c | head -n1)
          echo $VERSION > version.txt

      # 4. Upload firmware artifact (for debugging/download)
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/*.bin
            version.txt

      # 5. Create GitHub Release and upload firmware.bin and version.txt
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/*.bin
            version.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
