name: Build and Release Firmware

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 2. Cache ESP-IDF
      - name: Cache ESP-IDF
        uses: actions/cache@v4
        with:
          path: ~/.espressif
          key: espidf-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}-${{ hashFiles('**/sdkconfig') }}

      # 3. Setup ESP-IDF
      - name: Setup ESP-IDF
        uses: espressif/install-esp-idf-action@v1
        with:
          version: 'v5.4.1'

      # 4. Build firmware
      - name: Build project
        run: |
          source $IDF_PATH/export.sh
          idf.py build

      # 5. Extract firmware version and create version.txt
      - name: Create version.txt
        run: |
          VERSION=$(grep -Po '(?<=#define FIRMWARE_VERSION ")[^"]*' main/*.c | head -n1)
          echo $VERSION > version.txt

      # 6. Upload firmware artifact (for debugging/download)
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/*.bin
            version.txt

      # 7. Create GitHub Release and upload firmware.bin and version.txt
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/*.bin
            version.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
